tennis_pipeline:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: tennis_prod
      location: us-central1
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive